#ifndef NXOpen_ANNOTATIONS_QUERYPMIBUILDER_HXX_INCLUDED
#define NXOpen_ANNOTATIONS_QUERYPMIBUILDER_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Annotations_QueryPmiBuilder.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/Annotations_QueryPmiBuilder.hxx>
#include <NXOpen/Builder.hxx>
#include <NXOpen/SelectObjectList.hxx>
#include <NXOpen/libnxopencpp_annotations_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Annotations
    {
        class QueryPmiBuilder;
    }
    class Builder;
    class SelectObjectList;
    namespace Annotations
    {
        class _QueryPmiBuilderBuilder;
        class QueryPmiBuilderImpl;
        /**
            Represents a @link Annotations::QueryPmiBuilder Annotations::QueryPmiBuilder@endlink 
             <br> To create a new instance of this class, use @link Annotations::AnnotationManager::CreateQueryPmiBuilder Annotations::AnnotationManager::CreateQueryPmiBuilder@endlink  <br> 
        Default values.
        <table border="1"> 
         
        <tr><th> 
        Property</th>  <th> 
        Value</th> </tr>
        <tr><td> 
         
        CreateQueryResultsView </td> <td> 
         
        true </td> </tr> 

        </table>  

         <br>  Created in NX5.0.0.  <br>  
        */
        class NXOPENCPP_ANNOTATIONSEXPORT  QueryPmiBuilder : public Builder
        {
            private: QueryPmiBuilderImpl * m_querypmibuilder_impl;
            private: friend class  _QueryPmiBuilderBuilder;
            protected: QueryPmiBuilder();
            public: ~QueryPmiBuilder();
            /**Returns  the geometry 
             <br>  Created in NX5.0.0.  <br>  
             <br> License requirements : None */
            public: NXOpen::SelectObjectList * Geometry
            (
            );
            /**Sets  the create query results view 
             <br>  Created in NX8.5.0.  <br>  
             <br> License requirements : None */
            public: void SetCreateQueryResultsView
            (
                bool createQueryResultsView /** createqueryresultsview */ 
            );
            /**Returns  the create query results view 
             <br>  Created in NX8.5.0.  <br>  
             <br> License requirements : None */
            public: bool CreateQueryResultsView
            (
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
