#ifndef NXOpen_FACET_FACETEDEDGE_HXX_INCLUDED
#define NXOpen_FACET_FACETEDEDGE_HXX_INCLUDED
//--------------------------------------------------------------------------
//  Header for C++ interface to JA API
//--------------------------------------------------------------------------
//
//  Source File:
//     Facet_FacetedEdge.ja
//
//  Generated by:
//     apiwrap
//
//  WARNING:
//    This file is automatically generated - do not edit by hand
//
#ifdef _MSC_VER
#pragma once
#endif

#include <NXOpen/NXDeprecation.hxx>
#include <vector>
#include <NXOpen/NXString.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/DisplayableObject.hxx>
#include <NXOpen/IBaseCurve.hxx>
#include <NXOpen/INXObject.hxx>
#include <NXOpen/libnxopencpp_facet_exports.hxx>

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable:4996)
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

namespace NXOpen
{
    namespace Facet
    {
        class FacetedEdge;
    }
    namespace Assemblies
    {
        class Component;
    }
    class BasePart;
    class DisplayableObject;
    class IBaseCurve;
    class INXObject;
    namespace Facet
    {
        class _FacetedEdgeBuilder;
        class FacetedEdgeImpl;
        /** Represents a faceted edge. Instances of this class may be
                generated when recording a journal, but they cannot be created
                directly. 
            
         <br>  Created in NX5.0.0.  <br>  
        */
        class NXOPENCPP_FACETEXPORT  FacetedEdge : public DisplayableObject, public virtual IBaseCurve
        {
            private: FacetedEdgeImpl * m_facetededge_impl;
            private: friend class  _FacetedEdgeBuilder;
            protected: FacetedEdge();
            public: ~FacetedEdge();
            /** Returns the length of the object  @return  
             <br>  Created in NX3.0.0.  <br>  
             <br> License requirements : None */
            public: virtual double GetLength
            (
            );
            /**Returns  the reference state of a curve 
             <br>  Created in NX8.0.0.  <br>  
             <br> License requirements : None */
            public: virtual bool IsReference
            (
            );
        };
    }
}

#ifdef _MSC_VER
#pragma warning(pop)
#endif
#ifdef __GNUC__
#ifndef NX_NO_GCC_DEPRECATION_WARNINGS
#pragma GCC diagnostic warning "-Wdeprecated-declarations"
#endif
#endif

#undef EXPORTLIBRARY
#endif
